log:
  disable_sentry: true

db:
  url: postgres://test:test@localhost:25432/blobs?sslmode=disable

listener:
  addr: localhost:18080

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blobman
  service_port: 80
